server:
  port: 9000
spring:
  profiles:
    include:
      - secret
  data:
    mongodb:
      port: 27018
      host: localhost
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.4.1
logging:
  level:
    root: warn